# Generated by Django 5.2.7 on 2025-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('principal', models.CharField(blank=True, max_length=100, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
