# Generated by Django 5.2.7 on 2025-11-03 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='guruh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='student',
            name='jdu_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='JDU ID'),
            preserve_default=False,
        ),
    ]
